// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    var Bonus;
    Bonus = function(pos, vel, content, radiusSinVel) {
      this.pos = pos;
      this.vel = vel;
      this.content = content;
      this.radiusSinVel = radiusSinVel;
      this.isDead = false;
      return this.radiusAngle = this.radiusSinVel;
    };
    Bonus.ENERGY_LOSS = 5;
    Bonus.MASS_LOSS = 2;
    Bonus.ENERGY_COLOR = "#f0f";
    Bonus.ENERGY_HALF_OPACITY = 50;
    Bonus.MASS_COLOR = "#ff0";
    Bonus.MASS_HALF_OPACITY = 20;
    Bonus.RADIUS_MID = 0.4;
    Bonus.RADIUS_AMP = 0.05;
    Bonus.SPEED = 0.3;
    Bonus.RADIUS_SIN_VEL = 2 * Math.PI * 1.3;
    Bonus.prototype.update = function(t) {
      this.pos.x += this.vel.x * t;
      this.pos.y += this.vel.y * t;
      this.radiusAngle += this.radiusSinVel * t;
      this.radius = Bonus.RADIUS_MID + Math.sin(this.radiusAngle) * Bonus.RADIUS_AMP;
      if (this.content.energy != null) {
        this.content.energy -= Bonus.ENERGY_LOSS * t;
        this.isDead || (this.isDead = this.content.energy < 0);
      }
      if (this.content.mass != null) {
        this.content.mass -= Bonus.MASS_LOSS * t;
        return this.isDead || (this.isDead = this.content.mass < 0);
      }
    };
    Bonus.prototype.draw = function(ctx) {
      ctx.save();
      if (this.content.energy != null) {
        ctx.fillStyle = Bonus.ENERGY_COLOR;
        ctx.globalAlpha = Math.pow(0.5, Bonus.ENERGY_HALF_OPACITY / this.content.energy);
      } else if (this.content.mass != null) {
        ctx.fillStyle = Bonus.MASS_COLOR;
        ctx.globalAlpha = Math.pow(0.5, Bonus.MASS_HALF_OPACITY / this.content.mass);
      } else {
        throw new Error("unknown @content");
      }
      ctx.beginPath();
      ctx.arc(this.pos.x, this.pos.y, this.radius, 0, 2 * Math.PI);
      ctx.fill();
      return ctx.restore();
    };
    return Bonus;
  });

}).call(this);
