// Generated by CoffeeScript 1.6.3
(function() {
  define(["particle"], function(Particle) {
    var Bullet;
    Bullet = function(pos, vel, time) {
      this.pos = pos;
      this.vel = vel;
      this.time = time;
      return this.isDead = false;
    };
    Bullet.RADIUS = 0.1;
    Bullet.DESTROY_PROB = 0.2;
    Bullet.MASS = 2;
    Bullet.DAMAGE = 60;
    Bullet.prototype.move = Particle.prototype.move;
    Bullet.prototype.draw = function(ctx) {
      ctx.beginPath();
      ctx.arc(this.pos.x, this.pos.y, Bullet.RADIUS, 0, 2 * Math.PI);
      ctx.fillStyle = "#f00";
      return ctx.fill();
    };
    return Bullet;
  });

}).call(this);
