// Generated by CoffeeScript 1.6.3
(function() {
  define(["jquery", "game"], function($, Game) {
    var Menu;
    Menu = {};
    Menu.init = function($root) {
      var menu;
      menu = {
        dom: Menu.init.prepareDom($root),
        game: void 0
      };
      Menu.init.bindListeners(menu);
      Menu.show(menu);
      return menu;
    };
    Menu.init.prepareDom = function($root) {
      var $errorBox, $main, $playBtn, $playerCountInp, $startLivesInp;
      $main = $("<div />").appendTo($root);
      $playBtn = $("<input type='button' value='Play' name='play'>").appendTo($main);
      $playerCountInp = $("<input type='text' value='2' name='player-count'>").appendTo($main);
      $startLivesInp = $("<input type='text' value='10' name='start-lives'>").appendTo($main);
      $errorBox = $("<p class='error'></p>").appendTo($main);
      $errorBox.hide();
      return {
        $root: $root,
        $main: $main,
        $playBtn: $playBtn,
        $playerCountInp: $playerCountInp,
        $startLivesInp: $startLivesInp
      };
    };
    Menu.init.bindListeners = function(menu) {
      return menu.dom.$playBtn.click(function() {
        return Menu.play(menu);
      });
    };
    Menu.error = function(menu, msg) {
      menu.dom.$errorBox.text(msg);
      return menu.dom.$errorBox.show();
    };
    Menu.show = function(menu) {
      return menu.dom.$main.show();
    };
    Menu.hide = function(menu) {
      return menu.dom.$main.hide();
    };
    Menu.play = function(menu) {
      var playerCount, settings, startLives;
      playerCount = Math.floor(menu.dom.$playerCountInp.val() * 1);
      if (!(playerCount >= 1 && playerCount <= 4)) {
        Menu.error(menu, "Please select one to four players");
        return;
      }
      startLives = Math.floor(menu.dom.$startLivesInp.val() * 1);
      if (!(startLives > 0)) {
        Menu.error(menu, "Please set positive number of lives");
        return;
      }
      settings = {
        fps: 30,
        mapWidth: 100,
        mapHeight: 50,
        playerCount: playerCount,
        startLives: startLives
      };
      if (menu.game == null) {
        Menu.hide(menu);
        menu.game = Game.init(menu.dom.$root, settings, function() {
          Menu.show(menu);
          return menu.game = void 0;
        });
        return Game.start(menu.game);
      }
    };
    return Menu;
  });

}).call(this);
