// Generated by CoffeeScript 1.6.3
(function() {
  define(["jquery", "game"], function($, Game) {
    var Menu;
    return Menu = (function() {
      function Menu($root) {
        var _this = this;
        this.$root = $root;
        this.$menu = $("<div></div>").appendTo(this.$root);
        this.$playBtn = $("<button>Play</button>").appendTo(this.$menu);
        this.$playBtn.click(function() {
          return _this.play();
        });
      }

      Menu.prototype.play = function() {
        var settings;
        settings = {
          "fps": 30,
          "map width": 100,
          "map height": 50
        };
        if (this.game == null) {
          this.game = new Game(this.$root, settings);
          return this.game.start();
        }
      };

      return Menu;

    })();
  });

}).call(this);
