// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    var Particle;
    Particle = function(pos, vel, time, radius, color) {
      this.pos = pos;
      this.vel = vel;
      this.time = time;
      this.radius = radius;
      this.color = color;
      return this.isDead = false;
    };
    Particle.prototype.move = function(t) {
      this.time -= t;
      this.isDead || (this.isDead = this.time < 0);
      this.pos.x += this.vel.x * t;
      return this.pos.y += this.vel.y * t;
    };
    Particle.prototype.draw = function(ctx) {
      ctx.beginPath();
      ctx.arc(this.pos.x, this.pos.y, this.radius, 0, 2 * Math.PI);
      ctx.fillStyle = this.color;
      return ctx.fill();
    };
    return Particle;
  });

}).call(this);
