// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    var Particle;
    Particle = {};
    Particle.init = function(pos, vel, time, radius, color) {
      return {
        pos: pos,
        vel: vel,
        time: time,
        radius: radius,
        color: color,
        isDead: false
      };
    };
    Particle.move = function(particle, t) {
      particle.time -= t;
      particle.isDead || (particle.isDead = particle.time < 0);
      particle.pos.x += particle.vel.x * t;
      return particle.pos.y += particle.vel.y * t;
    };
    Particle.draw = function(particle, ctx) {
      ctx.beginPath();
      ctx.arc(particle.pos.x, particle.pos.y, particle.radius, 0, 2 * Math.PI);
      ctx.fillStyle = particle.color;
      return ctx.fill();
    };
    return Particle;
  });

}).call(this);
