// Generated by CoffeeScript 1.6.3
(function() {
  define(["map"], function(Map) {
    var Render;
    Render = {};
    Render.BORDER_COLOR = "#aaa";
    Render.STAT_FONT = "12px monospace";
    Render.STAT_COLOR = "#0f0";
    Render.game = function(game) {
      var h, scale, w, _ref, _ref1, _ref2, _ref3;
      switch (game.playerInfos.length) {
        case 1:
          _ref = [game.size.x, game.size.y, 18], w = _ref[0], h = _ref[1], scale = _ref[2];
          return Render.window(game, game.tanks[0], {
            x: 0,
            y: 0,
            w: w,
            h: h,
            scale: scale
          });
        case 2:
          _ref1 = [game.size.x / 2, game.size.y, 16], w = _ref1[0], h = _ref1[1], scale = _ref1[2];
          Render.window(game, game.tanks[0], {
            x: 0,
            y: 0,
            w: w,
            h: h,
            scale: scale
          });
          return Render.window(game, game.tanks[1], {
            x: w,
            y: 0,
            w: w,
            h: h,
            scale: scale
          });
        case 3:
          _ref2 = [game.size.x / 3, game.size.y, 15], w = _ref2[0], h = _ref2[1], scale = _ref2[2];
          Render.window(game, game.tanks[0], {
            x: 0,
            y: 0,
            w: w,
            h: h,
            scale: scale
          });
          Render.window(game, game.tanks[1], {
            x: w,
            y: 0,
            w: w,
            h: h,
            scale: scale
          });
          return Render.window(game, game.tanks[2], {
            x: 2 * w,
            y: 0,
            w: w,
            h: h,
            scale: scale
          });
        case 4:
          _ref3 = [game.size.x / 2, game.size.y / 2, 14], w = _ref3[0], h = _ref3[1], scale = _ref3[2];
          Render.window(game, game.tanks[0], {
            x: 0,
            y: 0,
            w: w,
            h: h,
            scale: scale
          });
          Render.window(game, game.tanks[1], {
            x: w,
            y: 0,
            w: w,
            h: h,
            scale: scale
          });
          Render.window(game, game.tanks[2], {
            x: 0,
            y: h,
            w: w,
            h: h,
            scale: scale
          });
          return Render.window(game, game.tanks[3], {
            x: w,
            y: h,
            w: w,
            h: h,
            scale: scale
          });
        default:
          throw new Error("Unknown layout for " + game.playerInfos.length + " players");
      }
    };
    Render.window = function(game, tank, win) {
      var center, ctx;
      center = tank.pos;
      ctx = game.dom.ctx;
      ctx.save();
      ctx.translate(win.x, win.y);
      ctx.beginPath();
      ctx.rect(0, 0, win.w, win.h);
      ctx.strokeStyle = Render.BORDER_COLOR;
      ctx.stroke();
      ctx.clip();
      ctx.save();
      ctx.translate(win.w * 0.5, win.h * 0.5);
      ctx.scale(win.scale, win.scale);
      ctx.translate(-center.x, -center.y);
      Render.map(ctx, game, win, center);
      Render.objects(ctx, game);
      ctx.restore();
      Render.stats(ctx, game, tank, win);
      return ctx.restore();
    };
    Render.objects = function(ctx, game) {
      var bonus, bullet, particle, tank_, _i, _j, _k, _l, _len, _len1, _len2, _len3, _ref, _ref1, _ref2, _ref3;
      ctx.save();
      _ref = game.tanks;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        tank_ = _ref[_i];
        tank_.draw(ctx);
      }
      _ref1 = game.bullets;
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        bullet = _ref1[_j];
        if (!bullet.isDead) {
          bullet.draw(ctx);
        }
      }
      _ref2 = game.particles;
      for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
        particle = _ref2[_k];
        if (!particle.isDead) {
          particle.draw(ctx);
        }
      }
      _ref3 = game.bonuses;
      for (_l = 0, _len3 = _ref3.length; _l < _len3; _l++) {
        bonus = _ref3[_l];
        if (!bonus.isDead) {
          bonus.draw(ctx);
        }
      }
      return ctx.restore();
    };
    Render.map = function(ctx, game, win, center) {
      var drawSquare, east, lastSquare, north, south, west, x, xMax, xMin, y, yMax, yMin, _ref, _ref1;
      _ref = Render.winToMap(win, center, {
        x: 0,
        y: 0
      }), west = _ref.x, north = _ref.y;
      _ref1 = Render.winToMap(win, center, {
        x: win.w,
        y: win.h
      }), east = _ref1.x, south = _ref1.y;
      xMin = Math.floor(west);
      xMax = Math.ceil(east);
      yMin = Math.floor(north);
      yMax = Math.ceil(south);
      lastSquare = void 0;
      drawSquare = function(x, y) {
        var square;
        square = Map.contains(game.map, x, y) ? Map.get(game.map, x, y) : Map.VOID;
        ctx.fillStyle = Map.squares[square].color;
        return ctx.fillRect(x, y, 1, 1);
      };
      x = xMin;
      while (x <= xMax) {
        y = yMin;
        while (y <= yMax) {
          drawSquare(x, y);
          y += 1;
        }
        x += 1;
      }
      return void 0;
    };
    Render.mapToWin = function(win, center, m) {
      return {
        x: win.scale * (m.x - center.x) + win.w * 0.5,
        y: win.scale * (m.y - center.y) + win.h * 0.5
      };
    };
    Render.winToMap = function(win, center, w) {
      return {
        x: center.x + (w.x - win.w * 0.5) / win.scale,
        y: center.y + (w.y - win.h * 0.5) / win.scale
      };
    };
    Render.stats = function(ctx, game, tank, win) {
      var game_state, info, progress, stat, weapon;
      info = game.playerInfos[tank.index];
      weapon = tank.weapons[tank.activeWeapon];
      progress = Array(Math.floor(weapon.temperature * 10) + 1).join(".");
      game_state = (function() {
        switch (game.mode.mode) {
          case "time":
            return "" + (Math.max(0, Math.floor(game.mode.time - game.time))) + " s";
          case "lives":
            return "" + (game.mode.lives - info.destroyed) + "/" + game.mode.lives + " lives";
          case "hits":
            return "" + info.hits + "/" + game.mode.hits + " hits";
        }
      })();
      stat = ("E " + (Math.floor(tank.energy)) + " ") + ("M " + (Math.floor(tank.mass)) + " ") + ("-" + info.destroyed + "/") + ("+" + info.hits + " | ") + ("" + weapon.spec.name + " ") + ("" + progress + " | ") + ("" + game_state);
      ctx.font = Render.STAT_FONT;
      ctx.textAlign = "left";
      ctx.fillStyle = Render.STAT_COLOR;
      return ctx.fillText(stat, 5, win.h - 5);
    };
    return Render;
  });

}).call(this);
