// Generated by CoffeeScript 1.6.3
(function() {
  require.config({
    baseUrl: "lib",
    paths: {
      jquery: "../vendor/jquery"
    }
  });

  require(["jquery", "menu"], function($, Menu) {
    return Menu($("#krt"));
  });

}).call(this);
