// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  self.onmessage = function(evt) {
    importScripts("../vendor/require.js");
    require.config({
      baseUrl: "./"
    });
    return require(["map_gen"], function(MapGen) {
      var map;
      map = MapGen.gen(evt.data);
      self.postMessage(map, [map.ary.buffer]);
      return self.close();
    });
  };

}).call(this);
